Add compatibility stuff for SunOS.

diff --git a/bin/mktemp b/bin/mktemp
--- a/bin/mktemp
+++ b/bin/mktemp
@@ -154,4 +154,23 @@ EOF
 
 [ "${0##*/}" = mktemp ] || return
 
+test_local='f () { local x=2; [ "$x" = 2 ]; }; x=1; f && [ "$x" = 1 ]'
+if ! eval "$test_local" >/dev/null 2>&1; then
+    for sh in /usr/gnu/bin/sh /usr/xpg4/bin/sh ksh; do
+        if [ -x "$sh" ] && "$sh" -c "$test_local" >/dev/null 2>&1; then
+            exec "$sh" "$0" "$@"
+        fi
+    done
+    echo "$0: 'local' builtin missing" >&1
+    exit 255
+fi
+
+case "$(uname -s)" in
+    SunOS)
+        awk () {
+            /usr/xpg4/bin/awk "$@"
+        }
+        ;;
+esac
+
 mktemp "$@"
